### ISSUE TITLE
AnouncementController improvement

### ISSUE THREAD

**Issue by nikoliasoroka** [VasylKits/AnnouncementWebApi#10]
1. Let's add the last endpoint asked in the test task (Show top 3 similar announcements).
2. Finish implementation of all endpoints.

**Comment by VasylKits** [comment]
I do something

**Comment by nikoliasoroka** [comment]
Grete job!

**Comment by VasylKits** [comment]
But las method Top 3 similar - how it do work?

**Comment by nikoliasoroka** [comment]
What do you mean? It works as you wrote it)
