### ISSUE TITLE
Move all business logic from controller to services

### ISSUE THREAD

**Issue by nikoliasoroka** [VasylKits/AnnouncementWebApi#16]
1. Create the interface IAnnouncementService with all appropriate methods signatures.
2. Implement this interface in AnnouncementService class.
3. Apply your service in the controller using Dependency Injection (DI - Constructor injection), read [this article](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0) or [this](https://stackify.com/net-core-dependency-injection/).

**Comment by VasylKits** [comment]
Done
